name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"
    - name: Docker build
      run: |
        echo "Iniciando build"
        docker build -t selvinmedina/graphql-actions:1.0.1 .
        echo "Fin del build"
    - name: Docker push
      run: |
        echo "Iniciando push"
        docker push selvinmedina/graphql-actions:1.0.1
        echo "Fin del push"
